Repository freee/freee-accounting-sdk-csharp, pull requests merged in 2020-09, with the labels that each got.

#15 バージョンに関連する注意文言追記
  README.md
Labels: documentation

#16 GitHub Actions を使ってビルド、発行を行う
  .github/workflows/build.yml
  .github/workflows/publish.yml
  azure-pipelines.yml
Labels: enhancement

#17 複数パッケージの発行に失敗するのを修正
  .github/workflows/publish.yml
Labels: bug
